### ISSUE TITLE
shadertoy with iTime does not work

### ISSUE THREAD

**Issue by mustafamasvi** [mat-sz/fxGlue#1]
Hi @mat-sz ,

How does iTime shadertoy work with fxGlue?
trying to implement https://www.shadertoy.com/view/XsGfWw

**Comment by mat-sz** [comment]
fxGlue only provides `iResolution` and `iTexture`. Anything else must be manually set with either:

```ts
glue.program('filter')?.uniforms.set('iTime', time);
```

or:

```ts
glue.program('filter')?.apply({ iTime: time });
```

**Comment by mustafamasvi** [comment]
Hi @mat-sz ,
I tried the above but the object won't move.
I believe the iTime and iTimeDelta should be passed in a different way.
I appreciate your quick reply, considering it holidays :)
